In [545]:
import numpy as np
import pandas as pd

In [546]:
tabela= pd.read_csv("heart-disease.csv")
tabela.head(50)

,Signal,3035 - 75th St W 29th Ave W,Unnamed: 2,Unnamed: 3
0,Start time,"Monday, May 17, 2021 12:00:00 AM",NaN,NaN
1,End time,"Monday, May 17, 2021 11:59:59 PM",NaN,NaN
2,Total Events,"108,248",NaN,NaN
3,Event Time,Event Code,Event Description,Event Parameter
4,05/17/21 00:00:02.100,0,Phase On,2
5,05/17/21 00:00:02.100,0,Phase On,6
6,05/17/21 00:00:02.100,1,Phase Begin Green,2
7,05/17/21 00:00:02.100,1,Phase Begin Green,6
8,05/17/21 00:00:02.100,23,Ped Phase Begin Dont Walk,2
9,05/17/21 00:00:02.100,23,Ped Phase Begin Dont Walk,4
10,05/17/21 00:00:02.100,23,Ped Phase Begin Dont Walk,6
11,05/17/21 00:00:02.100,23,Ped Phase Begin Dont Walk,8
12,05/17/21 00:00:02.100,46,Phase Omit On,1
13,05/17/21 00:00:02.100,46,Phase Omit On,2
14,05/17/21 00:00:02.100,46,Phase Omit On,3
15,05/17/21 00:00:02.100,46,Phase Omit On,4
16,05/17/21 00:00:02.100,46,Phase Omit On,5
17,05/17/21 00:00:02.100,46,Phase Omit On,6
18,05/17/21 00:00:02.100,46,Phase Omit On,7
19,05/17/21 00:00:02.100,46,Phase Omit On,8
20,05/17/21 00:00:02.100,46,Phase Omit On,15
21,05/17/21 00:00:02.100,48,Ped Omit On,1
22,05/17/21 00:00:02.100,48,Ped Omit On,3
23,05/17/21 00:00:02.100,48,Ped Omit On,5
24,05/17/21 00:00:02.100,48,Ped Omit On,7
25,05/17/21 00:00:02.100,48,Ped Omit On,9
26,05/17/21 00:00:02.100,48,Ped Omit On,10
27,05/17/21 00:00:02.100,48,Ped Omit On,11
28,05/17/21 00:00:02.100,48,Ped Omit On,12
29,05/17/21 00:00:02.100,48,Ped Omit On,13
30,05/17/21 00:00:02.100,48,Ped Omit On,14
31,05/17/21 00:00:02.100,48,Ped Omit On,15
32,05/17/21 00:00:02.100,48,Ped Omit On,16
33,05/17/21 00:00:02.100,131,Coord Pattern,254
34,05/17/21 00:00:02.100,132,Coord Cycle Length,100
35,05/17/21 00:00:02.100,134,Coord Split1,15
36,05/17/21 00:00:02.100,135,Coord Split2,48
37,05/17/21 00:00:02.100,136,Coord Split3,17
38,05/17/21 00:00:02.100,137,Coord Split4,20
39,05/17/21 00:00:02.100,138,Coord Split5,15
40,05/17/21 00:00:02.100,139,Coord Split6,48
41,05/17/21 00:00:02.100,140,Coord Split7,0
42,05/17/21 00:00:02.100,141,Coord Split8,37
43,05/17/21 00:00:02.100,142,Coord Split9,0
44,05/17/21 00:00:02.100,143,Coord Split10,0
45,05/17/21 00:00:02.100,144,Coord Split11,0
46,05/17/21 00:00:02.100,145,Coord Split12,0
47,05/17/21 00:00:02.100,146,Coord Split13,0
48,05/17/21 00:00:02.100,147,Coord Split14,0
49,05/17/21 00:00:02.100,148,Coord Split15,0

In [547]:
tabela["Signal"][4]

'05/17/21 00:00:02.100'

In [548]:
for col_name in tabela.columns: 
    print(col_name)

Signal
3035 - 75th St W 29th Ave W
Unnamed: 2
Unnamed: 3

In [549]:
bitni=["1","7","8","9","10","11"]
tabela1=pd.DataFrame(columns=["Signal", "3035 - 75th St W 29th Ave W","Unnamed: 2","Unnamed: 3"])

In [550]:
v1=[]
v2=[]
v3=[]
v4=[]

for i in range(len(tabela)):
    if tabela["3035 - 75th St W 29th Ave W"][i] in bitni and tabela["Unnamed: 3"][i]=="2":
        v1.append(tabela["Signal"][i])
        v2.append(tabela["3035 - 75th St W 29th Ave W"][i])
        v3.append(tabela["Unnamed: 2"][i])
        v4.append(tabela["Unnamed: 3"][i])
    
     
        
        
    else:
         continue

In [551]:
dikti= {
   "Signal": v1,
    "3035 - 75th St W 29th Ave W":v2,
    "Unnamed: 2":v3,
    "Unnamed: 3":v4
    
    
}

In [552]:
tabela1=pd.DataFrame(dikti)
tabela1

,Signal,3035 - 75th St W 29th Ave W,Unnamed: 2,Unnamed: 3
0,05/17/21 00:00:02.100,1,Phase Begin Green,2
1,05/17/21 02:04:54.700,7,Phase Green Termination,2
2,05/17/21 02:04:54.700,8,Phase Begin Yellow Clearance,2
3,05/17/21 02:05:00.000,9,Phase End Yellow Clearance,2
4,05/17/21 02:05:00.000,10,Phase Begin Red Clearance,2
...,...,...,...,...
2084,05/17/21 23:42:08.300,8,Phase Begin Yellow Clearance,2
2085,05/17/21 23:42:13.600,9,Phase End Yellow Clearance,2
2086,05/17/21 23:42:13.600,10,Phase Begin Red Clearance,2
2087,05/17/21 23:42:15.600,11,Phase End Red Clearance,2
2088,05/17/21 23:42:30.900,1,Phase Begin Green,2

In [553]:
zeljeni

['1', '7', '8', '9', '10', '11']

In [555]:
i=0
while i<len(tabela1):
    if  tabela1["3035 - 75th St W 29th Ave W"][i]==zeljeni[i%6]:
        tabela1["3035 - 75th St W 29th Ave W"][i]=tabela1["3035 - 75th St W 29th Ave W"][i%6]
    else:
        tabela1["3035 - 75th St W 29th Ave W"][i]=zeljeni[i]
    i=i+6

In [563]:
tabela1.to_csv('semafori.csv', index = False)